# Generated by Django 5.1.1 on 2026-02-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='last_student_seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='student_id_prefix',
            field=models.CharField(default='30', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='student_email_domain',
            field=models.CharField(default='students.kcau.ac.ke', max_length=100),
        ),
    ]
