# Generated by Django 5.1.1 on 2026-02-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
