# Generated by Django 5.1.1 on 2026-02-15 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_student_mpesa_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('join_url', models.URLField(max_length=500)),
                ('host_url', models.URLField(blank=True, max_length=500, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=50)),
                ('passcode', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lecturer')),
            ],
            options={
                'db_table': 'zoom_rooms',
            },
        ),
    ]
