# Generated by Django 5.1.1 on 2026-03-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_zoomroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='category',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('cat', 'CAT'), ('exam', 'Final Exam')], default='assignment', max_length=20),
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lecturer')),
            ],
            options={
                'db_table': 'learning_materials',
            },
        ),
    ]
