# Generated by Django 5.1.1 on 2026-02-03 11:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('current_phase', models.CharField(choices=[('DRAFT', 'Draft'), ('APPLIED', 'Applied'), ('VERIFIED', 'Verified'), ('SELECTED', 'Selected'), ('OFFERED', 'Offered'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Kenyan', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('previous_institution', models.CharField(max_length=100)),
                ('index_number', models.CharField(max_length=20)),
                ('mean_grade', models.CharField(max_length=5)),
                ('intake', models.CharField(max_length=20)),
                ('mode_of_study', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], max_length=20)),
                ('sponsor_type', models.CharField(choices=[('SELF', 'Self Sponsored'), ('GOVT', 'Government'), ('HELB', 'HELB')], default='SELF', max_length=20)),
            ],
            options={
                'db_table': 'admission_applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National ID / Passport'), ('BIRTH_CERT', 'Birth Certificate'), ('RESULT_SLIP', 'KCSE Result Slip'), ('LEAVING_CERT', 'School Leaving Certificate'), ('TRANSCRIPT', 'Academic Transcripts'), ('PASSPORT_PHOTO', 'Passport Photo'), ('MEDICAL_REPORT', 'Medical Examination Report'), ('PASSPORT', 'Valid International Passport'), ('STUDENT_VISA', 'Student Visa'), ('EQUIVALENCE_LETTER', 'Equivalence Letter')], max_length=20)),
                ('file', models.FileField(upload_to='admission_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'admission_documents',
            },
        ),
    ]
