# Generated by Django 5.1.1 on 2026-02-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='program_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.program'),
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admission.admissionapplication'),
        ),
    ]
