# Generated by Django 5.1.1 on 2026-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='checkout_request_id',
            new_name='provider_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='merchant_request_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_rail',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK_PESALINK', 'PesaLink (Bank Transfer)'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='MPESA', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
