# Generated by Django 5.1.1 on 2026-02-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_checkout_request_id_payment_provider_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_rail',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK_PESALINK', 'PesaLink (Bank Transfer)'), ('OTHER', 'Other')], default='MPESA', max_length=20),
        ),
    ]
